"""First commit

Revision ID: 863cc33dd118
Revises: 
Create Date: 2024-03-18 19:01:10.775934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863cc33dd118'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('available_quantity', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drink_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_quantity', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drink_drink_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drink_ingredient_id', sa.Integer(), nullable=True),
    sa.Column('drink_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drink_id'], ['drink.id'], ),
    sa.ForeignKeyConstraint(['drink_ingredient_id'], ['drink_ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drink_drink_ingredient')
    op.drop_table('drink_ingredient')
    op.drop_table('ingredient')
    op.drop_table('drink')
    # ### end Alembic commands ###
